name: CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  deployment:
    environment: prod
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install node (lts) and yarn
        run: |
          sudo apt install curl
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install --location=global yarn
      - name: Build yarn app
        run: |
          node -v
          yarn
          yarn build
      - name: Create SSH key an copy files
        run: |
          echo "$SSH_PRIVATE_KEY" > ./private.key
          sudo chmod 600 ./private.key
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          ssh -i ./private.key $SSH_USER@$SSH_HOST "cd $SSH_PATH && rm -rf ./*"
          scp -i ./private.key -r ./build $SSH_USER@$SSH_HOST:$SSH_PATH
          ssh -i ./private.key $SSH_USER@$SSH_HOST "cd $SSH_PATH && mv ./build/* ./"
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_PATH: ${{secrets.SSH_PATH}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
